version: '3'

networks:
  frontend:
    external: true

services:
  csgoscan:
    container_name: csgoscan
    image: registry.justmammoth.us/csgoscan/csgoscan:0.1
    restart: unless-stopped
    networks:
      - frontend
